name: Build .NET Projects in Bots Subfolders

on:
  push:
    branches: [ "master" ]
    paths: 
      - 'Bots/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Bots/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0' # Change to your desired .NET version

    - name: Restore & Build all .NET projects in Bots subfolders
      run: |
        find Bots -type f -name "*.csproj" | while read csproj; do
          echo "Building $csproj"
          dotnet restore "$csproj"
          dotnet build "$csproj" --configuration Release --no-restore
        done
